name: Download Files from Google Drive

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Files from Google Drive
      uses: gdrive-org/gdrive-download-action@v2
      with:
        api_key: "AIzaSyCxnKvYuxNIqobl6Op-XBC500r8qGIjgeY" # Your Google Drive API key
        src: "1-6VVb55xUMt1SV5aIKd0tvL9j0Fo1gJB" # Your Google Drive folder ID
        dest: "Szago/Szago.github.io/tree/main/EROS/Test" # Update with your desired destination path
